### ISSUE TITLE
clone下来 import 工程之后报错Error:No service of type Factory available in ProjectScopeServices.

### ISSUE THREAD

**Issue by AndrWang** [qiujuer/Genius-Android#85]
发现有人提了 issue
https://code.google.com/p/android/issues/detail?id=219692
直接将project 下的 gradle 中的classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'更新到1.4.1就可以了

**Comment by qiujuer** [comment]
你好 这个问题是因为 gradle 版本引起的发布库出错；在dev分支中是已经修复了的，如果用发布分支请不要同意升级gradle 版本即可；等后面dev分支稳定后会更新到master分支的。
