### ISSUE TITLE
Whether it can be compatible with the low version

### ISSUE THREAD

**Issue by wei3** [qiujuer/Genius-Android#87]
Error:Execution failed for task ':app:processBaiduDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [net.qiujuer.genius:ui:2.0.0-beta8] E:\chengye\app\build\intermediates\exploded-aar\net.qiujuer.genius\ui\2.0.0-beta8\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="net.qiujuer.genius.ui" to force usage

**Comment by qiujuer** [comment]
你好，这个错误是因为你的项目最低支持版本是api14，而我的框架是最低支持api15；项目的代码本身是可以支持到14的，但是觉得没必要支持那么低的现在的市场使用很少有14的了 所以就从 15 开始支持的。你可以尝试重新构建我的项目，或者更改你的项目版本为15.

多谢你的使用。
