### ISSUE TITLE
OOM Error

### ISSUE THREAD

**Issue by hjmJhon** [qiujuer/Genius-Android#88]
at net.qiujuer.genius.blur.StackBlur.blurNativelyPixels(StackBlur.java:91)

**Comment by qiujuer** [comment]
当模糊一个大图片的时候有一定可能会出现OOM，这个问题已经纳入优化中，在正式版中将会进行修复；多谢你的反馈。

**Comment by qiujuer** [comment]
该问题已修复，现在模糊大图可选新的策略来模糊图片；将在2.0.0正式版发布，明天就可以使用了。

**Comment by qiujuer** [comment]
请使用 2.0.0 版本的 
`compile 'net.qiujuer.genius:graphics:2.0.0'`

`Blur.onStackBlurClip(mSrc, 50)`
即可解决你的问题，感谢你的使用。
