### ISSUE TITLE
你他妈不要乱改原先的ui定义行不行？

### ISSUE THREAD

**Issue by 770842099** [qiujuer/Genius-Android#93]
把原先lay_2 lay_4都删掉了，导致今天我编译oschina 安卓源码失败（前天还是好的）
blur onStackBlur 方法的第三个参数也没了（原先可以选择true或者false） 的。   

升级版本一个原则就是不能把原先功能都删除了，即使原先功能是一坨屎。 谢谢

**Comment by qiujuer** [comment]
你好，该问题并不负责，因为之前的本就是预览版本 随时可能更改；而为了发布2.0.0正式版 这是不得不进行统一的工作。至于oschina源码 请直接下载最新源码，最新源码并没有这个问题；谢谢。
