### ISSUE TITLE
Vertical seek bar

### ISSUE THREAD

**Issue by Paul776** [qiujuer/Genius-Android#94]
Hello,

I would like to know how I can align a vertical seek bar to the parent left of my screen?
I have tried to rotate it but there is a huge padding left and right which makes it impossible for me to align it on the left for example

**Comment by qiujuer** [comment]
Hello,

We should first understand the principle of seek bar.
The bar default like this:
![s70112-162706](https://cloud.githubusercontent.com/assets/5687320/21882849/44917732-d8e7-11e6-8780-557289b0a79f.png)

Looks like seek bar is farther from the screen than button, but it's the same.
We look this:




```
    <net.qiujuer.genius.ui.widget.SeekBar
        android:id="@+id/seekBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="@dimen/font_16"
        genius:gAllowTrackClickToDrag="false"
        genius:gIndicator="none"
        genius:gMax="10"
        genius:gMin="0"
        genius:gRippleColor="@color/black_alpha_112"
        genius:gThumbSize="6dp"
        genius:gTickSize="2dp"
        genius:gTouchSize="16dp" />
```

**Comment by qiujuer** [comment]
Thank you very much, hope to relieve your confusion.

**Comment by qiujuer** [comment]
You can use it: https://github.com/qiujuer/Genius-Android/releases/tag/CAPRICE-V2.0.0
