### ISSUE TITLE
高斯模糊

### ISSUE THREAD

**Issue by zhengshiqiang47** [qiujuer/Genius-Android#97]
高斯模糊有对图片进行压缩么？会不会oom

**Comment by qiujuer** [comment]
你好，之前版本会出现OOM的可能性；但是最新的版本。我采取了分段式模糊再进行合并的操作，能够保证不会出现OOM；只要你的 Bitmap 本身加载时没有OOM，那就肯定不会了的。使用方式：
```
Blur.onStackBlurClip(toTransform, 20);
```
第一个参数是Bitmap，第二参数是模糊半径；会自动进行计算并进行分片，如果你需要强制分片可以使用：
```
Bitmap onStackBlurClip(Bitmap original, int radius, int parts);
```

一般而言都提倡使用第一种方式。
多谢。
